apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  labels:
    app: emqx
spec:
   image: emqx:5
   coreTemplate:
    spec:
      volumeClaimTemplates:
        storageClassName: {{ .Values.storageClassName }}
        resources:
          requests:
            storage: 5Gi
        accessModes:
          - ReadWriteOnce
      replicas: 3
   imagePullPolicy: IfNotPresent
   config:
      data: |
         listeners.tcp.test {
            bind = "0.0.0.0:1884"
            max_connections = 1024000
         }
   listenersServiceTemplate:
      spec:
         type: ClusterIP
   dashboardServiceTemplate:
      spec:
         type: ClusterIP