apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {{ .Values.ingress.annotations }}
  name: {{ .Values.wis2node }}
  labels:
    app: {{ .Values.wis2node }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  rules:
    - host: {{ .Values.wis2node }}.{{ .Values.ingress.hostname }}
      http:
        paths:
          - backend:
              service: 
                name: {{ .Values.wis2node }}
                port:
                  number: 80
            path: /
            pathType: {{ .Values.ingress.pathType }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {{ .Values.ingress.annotations }}
  name: emqx-dashboard
  labels:
    app: emqx
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  rules:
    - host: emqx-dashboard.{{ .Values.ingress.hostname }}
      http:
        paths:
          - backend:
              service: 
                name: emqx-dashboard
                port:
                  number: 18083
            path: /
            pathType: {{ .Values.ingress.pathType }}
