apiVersion: batch/v1
kind: Job
metadata:
  name: setup-redis-cluster
  annotations:
    "helm.sh/hook": "post-install" 
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    spec:
      containers:
      - name: script-runner
        image: redis:7.4.0
        command: ["/bin/sh", "-c"]
        args: ["redis-cli --cluster create redis-0.redis:6379 redis-1.redis:6379 redis-2.redis:6379 redis-3.redis:6379 redis-4.redis:6379 redis-5.redis:6379 --cluster-replicas 1 --cluster-yes"]
      restartPolicy: Never
